description: Pipeline for parsing gitlab api_json logs
processors:
- date:
    field: time
    formats:
      - ISO8601
# Set event fields
- set:
    field: event.module
    value: gitlab
- set:
    field: event.dataset
    value: gitlab.api
- set:
    field: event.kind
    value: event
- set:
    field: event.category
    value: web
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
# Rename fields to ECS
- rename:
    ignore_failure: true
    field: severity
    target_field: log.level
- rename:
    ignore_failure: true
    field: duration
    target_field: gitlab.api.duration
- rename:
    ignore_failure: true
    field: db
    target_field: gitlab.api.db
- rename:
    ignore_failure: true
    field: view
    target_field: gitlab.api.view
- rename:
    ignore_failure: true
    field: status
    target_field: http.response.status_code
- rename:
    ignore_failure: true
    field: method
    target_field: http.request.method
- rename:
    ignore_failure: true
    field: path
    target_field: url.path
- rename:
    ignore_failure: true
    field: remote_ip
    target_field: source.ip
- rename:
    ignore_failure: true
    field: route
    target_field: gitlab.api.route
- rename:
    ignore_failure: true
    field: user_id
    target_field: user.id
- rename:
    ignore_failure: true
    field: username
    target_field: user.name
- rename:
    ignore_failure: true
    field: queue_duration
    target_field: gitlab.api.queue_duration
- rename:
    ignore_failure: true
    field: gitaly_calls
    target_field: gitlab.api.gitaly_calls
- rename:
    ignore_failure: true
    field: gitaly_duration
    target_field: gitlab.api.gitaly_duration
# Fancy enrichment
- user_agent:
    field: ua
- geoip:
    field: source.ip
    target_field: source.geoip
# Script processor to go through the params field
- rename:
    field: params
    target_field: parameters
- set:
    field: gitlab.api.params
    value: {}
- script:
    lang: painless
    source: >-
      ArrayList gitlabparams = ctx.parameters;
      for (item in gitlabparams) {
        String key = item.key;
        String value = item.value;
        ctx.gitlab.api.params[key] = value;
      }
# Cleaning
- remove:
    field:
      - time
      - ua
      - parameters
