description: Pipeline for parsing gitlab application logs
processors:
- date:
    field: time
    formats:
      - ISO8601
# Set event fields
- set:
    field: event.module
    value: gitlab
- set:
    field: event.dataset
    value: gitlab.api
- set:
    field: event.kind
    value: event
- set:
    field: event.category
    value: web
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
# Rename fields to ECS
- rename:
    ignore_failure: true
    field: severity
    target_field: log.level
- rename:
    ignore_failure: true
    field: correlation_id
    target_field: gitlab.correlation_id
